### ISSUE TITLE
passingByThreshold

### ISSUE THREAD

**Issue by mcattle** [jesmak/MMM-FlightRadarTracker#1]
Is the passingByThreshold in meters or feet, and is it altitude above sea level or current ground level?

**Comment by jesmak** [comment]
Altitude comes directly from Flightradar24 and the title there is corrected pressure altitude above mean sea level. Value is then converted to metric or imperial depending on what you've put to _altitudeUnits_ setting. _passingByThreshold_ uses the same setting. So if you want meters, set _altitudeUnits_ to _metric_. If you want feet, set it to _imperial_.
