### ISSUE TITLE
Show origin/destination information

### ISSUE THREAD

**Issue by rubenix** [jesmak/MMM-FlightRadarTracker#2]
Is it possible to show origin & destination info?
I just headed on to flightradar24.com and I can see origin /destinination airport for each aircraft; don't know if data its fetched tho...its working finr on my mirror; just wanted to know if I can show this info.
Thanks!

**Comment by jesmak** [comment]
Technically it should be possible, but there's no support in MMM-FlightRadarTracker for it yet. I'll have a look and see what would be the best way to present the info.

**Comment by rubenix** [comment]
ok, it would be nice to show it. Thanks a milion!

**Comment by rubenix** [comment]
& thanks for a descriptive title on issue; actually not an issue but an enhancement, isn't it?

**Comment by jesmak** [comment]
It's an enhancement yes, but I don't think there's any way to set the issue type in github (or, I just don't know how to use this). This is a good way to track feature requests too.

**Comment by rubenix** [comment]
Yes theres a 'label' for enhancement but I think its the PR owner who can set it tho; Im quite new to github too xDDD

https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests

Hope it helps!

**Comment by jesmak** [comment]
A new setting has now been added (showRoute). If enabled, flight origin and destination will be shown. See screenshot in readme for an example.
