### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Wominator** [jesmak/MMM-FlightRadarTracker#3]
Dear jesmak,

I installed the module, but nothing happens. I went to the instructions again and again, double checked on Flightradar, there  should be some planes in the sky, but nothing. Is there something missing? An API-Key or something like that? 

Regards from Berlin
Wominator

**Comment by jesmak** [comment]
There should be no need for API keys or anything like that. Can you paste me your configuration so I can check/test if it's ok.

**Comment by Wominator** [comment]
Thanks for the quick response! 

`		{
				module: 'MMM-FlightRadarTracker',
				header: 'FlightRadar24',
				position: 'top_right',
				config: {
					updateInterval: 180,
					distance: 50,
					passingByThreshold: -1,
					limit: 5,
					speedUnits: 'metric',
					altitudeUnits: 'metric',
					// centerPoint: [52.527764, 13.3783161],
					centerPoint: [50.0278855, 8.6276626],
					showAirline: true,
					showType: true,
					showSpeed: true,
					showAltitude: true,
					showHeading: true,
					showDirectionAsArrow: true,
					showRoute: true,
					noPlanesLabel: 'Keine Flüge',
					atTheWindowLabel: 'am Fenster',
					passingByLabel: 'Überflug'
					}
		},`

**Comment by Wominator** [comment]
`{ 
module: 'MMM-FlightRadarTracker', 
header: 'FlightRadar24', 
position: 'top_right', 
config: { 
updateInterval: 180, 
distance: 50, 
passingByThreshold: -1, 
limit: 5, 
speedUnits: 'metric', 
altitudeUnits: 'metric', 
// centerPoint: [52.527764, 13.3783161], 
centerPoint: [50.0278855, 8.6276626], showAirline: true, showType: true, showSpeed: true, showAltitude: true, showHeading: true, showDirectionAsArrow: true, showRoute: true, noPlanesLabel: 'Keine Flüge', atTheWindowLabel: 'am Fenster', passingByLabel: 'Überflug' } },`

**Comment by Wominator** [comment]
{
				module: 'MMM-FlightRadarTracker',
				header: 'FlightRadar24',
				position: 'top_right',
				config: {
					updateInterval: 180,
					distance: 50,
					passingByThreshold: -1,
					limit: 5,
					speedUnits: 'metric',
					altitudeUnits: 'metric',
					// centerPoint: [52.527764, 13.3783161],
					centerPoint: [50.0278855, 8.6276626],
					showAirline: true,
					showType: true,
					showSpeed: true,
					showAltitude: true,
					showHeading: true,
					showDirectionAsArrow: true,
					showRoute: true,
					noPlanesLabel: 'keena da',
					atTheWindowLabel: 'am Fenster',
					passingByLabel: 'Überflug'
					}
		},

Second try :)

**Comment by jesmak** [comment]
I tested with your exact configuration and I do get lots of flight info immediately to my MagicMirror. I'm not sure what might be wrong with your environment. Maybe you could test by starting MagicMirror in server only mode to see if there are any visible errors? You can do this by stopping your MagicMirror service, then in Linux shell go to your MagicMirror directory and type "node serveronly". If there are any error in the output stream, could you send them to me.

**Comment by Wominator** [comment]
Dear jesmak,
I tested it know on my other mirror at home and it works fine. The one in my office I'll test tomorrow again and I will come back to you. Thanks a lot for your support and quick response!
Regards 
Wominator
