### ISSUE TITLE
The module displays "function String() { [native code] }" instead of flight information

### ISSUE THREAD

**Issue by sharemedics** [jesmak/MMM-FlightRadarTracker#5]
I am not sure if I am doing something wrong but I tried to enable this and instead of getting the planes, I am getting a "function String() { [native code] }". Here is a screenshot,

<img width="394" alt="Screen Shot 2020-09-06 at 2 47 02 PM" src="https://user-images.githubusercontent.com/12889049/92334044-e13a5300-f04f-11ea-990a-72b801fc9cf4.png">

**Comment by sharemedics** [comment]
Nevermind, this was my fault. I had a typo that caused this.

**Comment by jesmak** [comment]
Can you share your configuration so I could test it out? Seems pretty
strange, haven't seen this before.

su 6. syysk. 2020 klo 22.47 sharemedics (notifications@github.com)
kirjoitti:

**Comment by sharemedics** [comment]
Hey there! I think this was an error on my part.
